return {
	{
		"jakewvincent/mkdnflow.nvim",
		config = function()
			require("mkdnflow").setup({
				modules = {
					bib = false,
					buffers = true,
					conceal = false,
					cursor = false,
					folds = true,
					links = false,
					lists = true,
					maps = true,
					paths = false,
					tables = true,
					yaml = false,
					cmp = false,
				},
				to_do = {
					symbols = {
						-- basic
						" ",
						"/",
						"x",
						"-",
						"<",
						">",
						-- extras
						"?",
						"!",
						"*",
						'"',
						"l",
						"b",
						"i",
						"S",
						"I",
						"p",
						"c",
						"f",
						"k",
						"w",
						"u",
						"d",
					},
					update_parents = true,
					not_started = " ",
					in_progress = "/",
					complete = "x",
				},
				mappings = {
					MkdnEnter = false, -- {{'n', 'v'}, '<CR>'},
					MkdnTab = false,
					MkdnSTab = false,
					MkdnNextLink = false, -- {'n', '<Tab>'},
					MkdnPrevLink = false, -- {'n', '<S-Tab>'},
					MkdnNextHeading = false, -- { "n", "]]" },
					MkdnPrevHeading = false, -- { "n", "[[" },
					MkdnGoBack = false, -- { "n", "<BS>" },
					MkdnGoForward = false, -- { "n", "<Del>" },
					MkdnCreateLink = false, -- see MkdnEnter
					MkdnCreateLinkFromClipboard = false, -- { { "n", "v" }, "<leader>p" }, -- see MkdnEnter
					MkdnFollowLink = false, -- see MkdnEnter
					MkdnDestroyLink = false, -- {'n', '<M-CR>'},
					MkdnTagSpan = false, -- {'v', '<M-CR>'},
					MkdnMoveSource = false, -- {'n', '<F2>'},
					MkdnYankAnchorLink = false, -- {'n', 'yaa'},
					MkdnYankFileAnchorLink = false, -- {'n', 'yfa'},
					MkdnIncreaseHeading = false, -- {'n', '+'},
					MkdnDecreaseHeading = false, -- {'n', '-'},
					MkdnToggleToDo = false, -- {{'n', 'v'}, '<C-Space>'},
					MkdnNewListItem = false,
					MkdnNewListItemBelowInsert = false, -- {'n', 'o'},
					MkdnNewListItemAboveInsert = false, -- {'n', 'O'},
					MkdnExtendList = false,
					MkdnUpdateNumbering = { "n", "<leader>tr" }, -- {'n', '<leader>nn'},
					MkdnTableNextCell = false, -- {'i', '<Tab>'},
					MkdnTablePrevCell = false, -- {'i', '<S-Tab>'},
					MkdnTableNextRow = false,
					MkdnTablePrevRow = false, -- {'i', '<M-CR>'},
					MkdnTableNewRowBelow = false, -- {'n', '<leader>ir'},
					MkdnTableNewRowAbove = false, -- {'n', '<leader>iR'},
					MkdnTableNewColAfter = false, -- {'n', '<leader>ic'},
					MkdnTableNewColBefore = false, -- {'n', '<leader>iC'},
					MkdnFoldSection = { "n", "<leader>tf" }, -- {'n', '<leader>f'},
					MkdnUnfoldSection = { "n", "<leader>tF" }, -- {'n', '<leader>F'},
					-- new
					MkdnTableFormat = { "n", "<leader>tt" },
				},
			})
		end,
	},
}
